# Generated by Django 6.0.4 on 2026-04-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('GREEN', 'Código Verde - Bajo'), ('YELLOW', 'Código Amarillo - Intermedio'), ('RED', 'Código Rojo - Alto')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
