# Generated by Django 5.2.13 on 2026-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_emergencysignal_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencysignal',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencysignal',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
