# Generated by Django 5.2.13 on 2026-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergencysignal_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencysignal',
            name='message',
        ),
    ]
